### ISSUE TITLE
Any plans to replace PyTorch's CPU `sum` implementation with one of these?

### ISSUE THREAD

**Issue by imaginary-person** [r-barnes/reproducible_floating_sums#1]
Hello, I'm just curious if there are any plans to replace PyTorch's CPU SumKernel implementation for floating point types (which uses pairwise summation) with one of these?

I'm yet to test them but am curious as to how well they perform with multiple threads, and if they have better accuracy than pairwise summation.

Thank you!

**Comment by r-barnes** [comment]
Pairwise summation has _O(ε sqrt(log n))_ error and Kahan summation has _O(ε)_ error where ε is about 2^-53 for a double.

The reproducible summation has an error of _n*2^-80 max |x_i| + 7ε|sum(x_i)|_. In my experiments described [here](https://stackoverflow.com/a/67714555/752843) the reproducible and Kahan summations yield the same values.

I do not think this will replace pairwise summation in PyTorch: both Kahan and Reproducible summation take longer than pairwise summation. Pairwise summation is already deterministic (I think), so there's not a gain there. If additional accuracy were needed, Kahan summation could have been used already.

However, if you would like to raise this question [as a PyTorch issue](https://github.com/pytorch/pytorch/issues) (sorry to juggle you around), we could discuss it there with the PyTorch team. If you do open an issue there, please tag me in it.

**Comment by imaginary-person** [comment]
Thank you for the info!
Your write-up on StackOverflow is highly informative as well!
