### ISSUE TITLE
License status?

### ISSUE THREAD

**Issue by maddyscientist** [r-barnes/reproducible_floating_sums#2]
Thank you for this work, it is a great demonstration of the reproducible summation algorithms.  

The license of this source code doesn't seem to be specified.  Would the author consider making this work available under a BSD / MIT / Apache license?

Thanks

**Comment by maddyscientist** [comment]
Any chance of an update here?  I'd love to include look into porting this these algorithms to a GPU, and this looks like a great starting point.  Any derived work would remain open source, if it matters.

**Comment by r-barnes** [comment]
@maddyscientist - I've moved this onto the MIT License. Note that some code is drawn from https://github.com/peterahrens/ReproBLAS, which uses a University of California license ([details](https://github.com/peterahrens/ReproBLAS/blob/master/LICENSE)).

Sorry for the delay. I'd be interested to know how this works out for you :-)

**Comment by maddyscientist** [comment]
@r-barnes thank you very much.  I'll update you if I make if and when I make any progress on this front.

**Comment by maddyscientist** [comment]
Just to note that I've mostly completed a port to CUDA.  I've essentially ported ahrens2020.cpp to CUDA (in ahrens2020_cuda.cu).  Still some optimization left to be done, but it's performing reasonably (get's up to 450 GB/s on a GPU that can get around 650 GB/s on a naive summation algorithm).

Up until now, I've kept fairly close to the style of the original code, but I may diverge / extend it to include other summation algorithms, e.g., higher-level floating-point expansions, fp128, double-double, etc.

**Comment by maddyscientist** [comment]
My branch is here: https://github.com/maddyscientist/reproducible_floating_sums/tree/feature/cuda

**Comment by r-barnes** [comment]
@maddyscientist - Very cool! Thanks for the link.
